=== Open-Attestation/schemata/src/sg/gov/moh/pdt-healthcert/1.0/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://schemata.openattestation.com/sg/gov/moh/pdt-healthcert/1.0",
  "type": "object",
  "definitions": {
    "Reference": {
      "description": "A reference from one resource to another",
      "type": "object",
      "required": ["reference"],
      "properties": {
        "reference": {
          "description": "Literal reference, Relative, internal or absolute URL",
          "type": "string"
        }
      },
      "additionalProperties": true
    },
    "CodeableConcept": {
      "description": "A concept that may be defined by a formal reference to a terminology or ontology or may be provided by text.",
      "type": "object",
      "required": ["coding"],
      "properties": {
        "coding": {
          "description": "A reference to a code defined by a terminology system.",
          "type": "array",
          "items": {
            "type": "object",
            "required": ["system", "code", "display"],
            "properties": {
              "system": {
                "description": "The identification of the code system that defines the meaning of the symbol in the code.",
                "type": "string",
                "examples": ["http://snomed.info/sct"],
                "format": "uri"
              },
              "code": {
                "type": "string",
                "examples": ["258500001"]
              },
              "display": {
                "description": "A representation of the meaning of the code in the system, following the rules of the system.",
                "type": "string",
                "examples": ["Nasopharyngeal swab"]
              }
            },
            "additionalProperties": true
          },
          "minItems": 1
        }
      },
      "additionalProperties": true
    },
    "Patient": {
      "description": "Demographics and other administrative information about an individual or animal receiving care or other health-related services.",
      "type": "object",
      "required": ["resourceType", "extension", "identifier", "name", "gender", "birthDate"],
      "properties": {
        "fullUrl": {
          "type": "string",
          "examples": ["urn:uuid:bbbb1321-4af5-424c-a0e1-ed3aab1c349d"]
        },
        "resourceType": {
          "type": "string",
          "enum": ["Patient"]
        },
        "extension": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "required": ["url", "code"],
            "properties": {
              "url": {
                "type": "string",
                "examples": ["http://hl7.org/fhir/StructureDefinition/patient-nationality"]
              },
              "code": {
                "type": "object",
                "required": ["text"],
                "properties": {
                  "text": {
                    "type": "string",
                    "examples": ["SG"]
                  }
                },
                "additionalProperties": true
              }
            },
            "additionalProperties": true
          }
        },
        "identifier": {
          "description": "An identifier for this patient.",
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "required": ["type", "value"],
            "properties": {
              "type": {
                "oneOf": [
                  {
                    "type": "string",
                    "examples": ["PPN"]
                  },
                  {
                    "type": "object",
                    "required": ["text"],
                    "properties": {
                      "text": {
                        "type": "string",
                        "examples": ["NRIC"]
                      }
                    }
                  }
                ]
              },
              "value": {
                "type": "string",
                "examples": ["E7831177G"]
              }
            },
            "additionalProperties": true
          }
        },
        "name": {
          "description": "A name associated with the individual.",
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "required": ["text"],
            "properties": {
              "text": {
                "description": "Specifies the entire name as it should be displayed e.g. on an application UI. This may be provided instead of or as well as the specific parts.",
                "type": "string",
                "examples": ["Tan Chen Chen"]
              }
            },
            "additionalProperties": true
          }
        },
        "gender": {
          "description": "Administrative Gender - the gender that the patient is considered to have for administration and record keeping purposes.",
          "enum": ["male", "female"]
        },
        "birthDate": {
          "description": "The date of birth for the individual.",
          "type": "string",
          "format": "date"
        }
      },
      "additionalProperties": true
    },
    "Specimen": {
      "description": "A sample to be used for analysis.",
      "type": "object",
      "required": ["resourceType", "type", "collection"],
      "properties": {
        "fullUrl": {
          "type": "string",
          "examples": ["urn:uuid:bbbb1321-4af5-424c-a0e1-ed3aab1c349d"]
        },
        "resourceType": {
          "type": "string",
          "enum": ["Specimen"]
        },
        "type": {
          "description": "The kind of material that forms the specimen.",
          "$ref": "#/definitions/CodeableConcept"
        },
        "collection": {
          "description": "Details concerning the specimen collection.",
          "type": "object",
          "required": ["collectedDateTime"],
          "properties": {
            "collectedDateTime": {
              "description": "Time when specimen was collected from subject - the physiologically relevant time.",
              "type": "string",
              "format": "date-time"
            }
          },
          "additionalProperties": true
        }
      },
      "additionalProperties": true
    },
    "Observation": {
      "description": "Measurements and simple assertions made about a patient, device or other subject.",
      "type": "object",
      "required": ["resourceType", "code", "valueCodeableConcept", "effectiveDateTime", "qualification", "status"],
      "properties": {
        "fullUrl": {
          "type": "string",
          "examples": ["urn:uuid:bbbb1321-4af5-424c-a0e1-ed3aab1c349d"]
        },
        "resourceType": {
          "type": "string",
          "enum": ["Observation"]
        },
        "identifier": {
          "description": "A unique identifier assigned to this observation.",
          "type": "array",
          "items": {
            "type": "object",
            "required": ["value", "type"],
            "properties": {
              "value": {
                "type": "string",
                "description": "lab accession number",
                "examples": ["123456789"]
              },
              "type": {
                "type": "string",
                "examples": ["ACSN"]
              }
            },
            "additionalProperties": true
          },
          "minItems": 1
        },
        "code": {
          "description": "Describes what was observed. Sometimes this is called the observation \"name\".",
          "$ref": "#/definitions/CodeableConcept"
        },
        "valueCodeableConcept": {
          "description": "The information determined as a result of making the observation, if the information has a simple value.",
          "$ref": "#/definitions/CodeableConcept"
        },
        "effectiveDateTime": {
          "description": "The time or time-period the observed value is asserted as being true. For biological subjects - e.g. human patients - this is usually called the \"physiologically relevant time\". This is usually either the time of the procedure or of specimen collection, but very often the source of the date/time is not known, only the date/time itself.",
          "type": "string",
          "format": "date-time"
        },
        "performer": {
          "description": "Who was responsible for asserting the observed value as \"true\".",
          "type": "object",
          "required": ["name"],
          "properties": {
            "name": {
              "type": "array",
              "items": {
                "type": "object",
                "required": ["text"],
                "properties": {
                  "text": {
                    "description": "Specifies the entire name as it should be displayed e.g. on an application UI. This may be provided instead of or as well as the specific parts.",
                    "type": "string",
                    "examples": ["Dr Michael Lim"]
                  }
                },
                "additionalProperties": true
              },
              "minItems": 1
            }
          },
          "additionalProperties": true
        },
        "qualification": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["identifier", "issuer"],
            "properties": {
              "identifier": {
                "type": "string",
                "examples": ["MCR 123214"]
              },
              "issuer": {
                "type": "string",
                "examples": ["MOH"]
              }
            },
            "additionalProperties": true
          },
          "minItems": 1
        },
        "status": {
          "description": "The status of the result value.",
          "enum": [
            "registered",
            "preliminary",
            "final",
            "amended",
            "corrected",
            "cancelled",
            "entered-in-error",
            "unknown"
          ]
        },
        "specimen": {
          "$ref": "#/definitions/Reference"
        },
        "performerReference": {
          "description": "Who is responsible for the observation",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Reference"
          }
        }
      },
      "additionalProperties": true
    },
    "Organization": {
      "description": "A formally or informally recognized grouping of people or organizations formed for the purpose of achieving some form of collective action.  Includes companies, institutions, corporations, departments, community groups, healthcare practice groups, payer/insurer, etc.",
      "type": "object",
      "required": ["resourceType", "name", "type", "contact"],
      "properties": {
        "fullUrl": {
          "type": "string",
          "examples": ["urn:uuid:bbbb1321-4af5-424c-a0e1-ed3aab1c349d"]
        },
        "resourceType": {
          "type": "string",
          "enum": ["Organization"]
        },
        "name": {
          "description": "A name associated with the organization.",
          "type": "string",
          "examples": ["Raffles Medical Clinic", "MacRitchie Laboratory"]
        },
        "type": {
          "description": "The kind(s) of organization that this is.",
          "type": "string",
          "examples": ["Licensed Healthcare Provider", "Accredited Laboratory"]
        },
        "endpoint": {
          "description": "Technical endpoints providing access to services operated for the organization.",
          "type": "object",
          "required": ["address"],
          "properties": {
            "address": {
              "type": "string",
              "format": "uri",
              "examples": ["https://www.rafflesmedical.com.sg"]
            }
          },
          "additionalProperties": true
        },
        "contact": {
          "description": "Contact for the organization for a certain purpose.",
          "type": "object",
          "required": ["telecom", "address"],
          "properties": {
            "telecom": {
              "description": "A contact detail (e.g. a telephone number or an email address) by which the party may be contacted.",
              "type": "array",
              "items": {
                "type": "object",
                "required": ["system", "value"],
                "properties": {
                  "system": {
                    "description": "Telecommunications form for contact point - what communications system is required to make use of the contact.",
                    "enum": ["phone", "fax", "email", "pager", "url", "sms", "other"],
                    "examples": ["phone"]
                  },
                  "value": {
                    "description": "The actual contact point details, in a form that is meaningful to the designated communication system (i.e. phone number or email address).",
                    "type": "string",
                    "examples": ["+6563113111", "+6562711188"]
                  }
                },
                "additionalProperties": true
              },
              "minItems": 1
            },
            "address": {
              "description": "Visiting or postal addresses for the contact.",
              "type": "object",
              "required": ["type", "use", "text"],
              "properties": {
                "type": {
                  "description": "Distinguishes between physical addresses (those you can visit) and mailing addresses (e.g. PO Boxes and care-of addresses). Most addresses are both.",
                  "enum": ["postal", "physical", "both"],
                  "examples": ["postal"]
                },
                "use": {
                  "description": "The purpose of this address.",
                  "enum": ["home", "work", "temp", "old", "billing"],
                  "examples": ["home"]
                },
                "text": {
                  "description": "Specifies the entire address as it should be displayed e.g. on a postal label. This may be provided instead of or as well as the specific parts.",
                  "type": "string",
                  "examples": [
                    "MacRitchie Hospital Thomson Road Singapore 123000",
                    "2 Thomson Avenue 4 Singapore 098888"
                  ]
                }
              },
              "additionalProperties": true
            }
          },
          "additionalProperties": true
        }
      },
      "additionalProperties": true
    }
  },
  "required": ["id", "name", "validFrom", "fhirVersion", "fhirBundle"],
  "properties": {
    "id": {
      "type": "string",
      "examples": ["TEST001"]
    },
    "name": {
      "type": "string",
      "examples": ["HealthCert"]
    },
    "logo": {
      "type": "string",
      "description": "base64 encoded image"
    },
    "validFrom": {
      "type": "string",
      "format": "date-time",
      "description": "Date and time from which the document is considered valid"
    },
    "fhirVersion": {
      "type": "string",
      "examples": ["4.0.1"]
    },
    "fhirBundle": {
      "type": "object",
      "description": "A container for a collection of resources.",
      "required": ["resourceType", "type", "entry"],
      "properties": {
        "resourceType": {
          "description": "This is a Bundle resource",
          "enum": ["Bundle"]
        },
        "type": {
          "description": "Indicates the purpose of this bundle - how it is intended to be used.",
          "enum": ["collection"],
          "examples": ["collection"]
        },
        "entry": {
          "description": "An entry in a bundle resource - will contain information about Patient, Speciment, Observation or Organization.",
          "type": "array",
          "minItems": 4,
          "items": {
            "oneOf": [
              {
                "$ref": "#/definitions/Patient"
              },
              {
                "$ref": "#/definitions/Specimen"
              },
              {
                "$ref": "#/definitions/Observation"
              },
              {
                "$ref": "#/definitions/Organization"
              }
            ]
          }
        }
      },
      "additionalProperties": true
    }
  },
  "additionalProperties": true
}

=== Open-Attestation/schemata/src/sg/gov/moh/healthcert/1.0/sample-document-with-references.json
{
  "id": "TEST001",
  "name": "HealthCert",
  "validFrom": "2020-11-20",
  "fhirVersion": "4.0.1",
  "fhirBundle": {
    "resourceType": "Bundle",
    "type": "collection",
    "entry": [
      {
        "fullUrl": "urn:uuid:aaaa1321-4af5-424c-a0e1-ed3aab1c349d",
        "resourceType": "Patient",
        "extension": [
          {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-nationality",
            "code": {
              "text": "SG"
            }
          }
        ],
        "identifier": [
          {
            "type": "PPN",
            "value": "E7831177G"
          },
          {
            "type": {
              "text": "NRIC"
            },
            "value": "S9098989Z"
          }
        ],
        "name": [
          {
            "text": "Tan Chen Chen"
          }
        ],
        "gender": "female",
        "birthDate": "1990-01-15"
      },
      {
        "fullUrl": "urn:uuid:bbbb1321-4af5-424c-a0e1-ed3aab1c349d",
        "resourceType": "Specimen",
        "type": {
          "coding": [
            {
              "system": "http://snomed.info/sct",
              "code": "258500001",
              "display": "Nasopharyngeal swab"
            }
          ]
        },
        "collection": {
          "collectedDateTime": "2020-09-27T06:15:00Z"
        }
      },
      {
        "fullUrl": "urn:uuid:cccc1321-4af5-424c-a0e1-ed3aab1c349d",
        "specimen": {
          "reference": "urn:uuid:bbbb1321-4af5-424c-a0e1-ed3aab1c349d"
        },
        "performerReference": [
          {
            "reference": "urn:uuid:dddd1321-4af5-424c-a0e1-ed3aab1c349d"
          },
          {
            "reference": "urn:uuid:eeee1321-4af5-424c-a0e1-ed3aab1c349d"
          }
        ],
        "resourceType": "Observation",
        "identifier": [
          {
            "value": "123456789",
            "type": "ACSN"
          }
        ],
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "94531-1",
              "display": "Reverse transcription polymerase chain reaction (rRT-PCR) test"
            }
          ]
        },
        "valueCodeableConcept": {
          "coding": [
            {
              "system": "http://snomed.info/sct",
              "code": "260385009",
              "display": "Negative"
            }
          ]
        },
        "effectiveDateTime": "2020-09-28T06:15:00Z",
        "status": "final",
        "performer": {
          "name": [
            {
              "text": "Dr Michael Lim"
            }
          ]
        },
        "qualification": [
          {
            "identifier": "MCR 123214",
            "issuer": "MOH"
          }
        ]
      },
      {
        "fullUrl": "urn:uuid:dddd1321-4af5-424c-a0e1-ed3aab1c349d",
        "resourceType": "Organization",
        "name": "MacRitchie Medical Clinic",
        "type": "Licensed Healthcare Provider",
        "endpoint": {
          "address": "https://www.macritchieclinic.com.sg"
        },
        "contact": {
          "telecom": [
            {
              "system": "phone",
              "value": "+6563113111"
            }
          ],
          "address": {
            "type": "physical",
            "use": "work",
            "text": "MacRitchie Hospital Thomson Road Singapore 123000"
          }
        }
      },
      {
        "fullUrl": "urn:uuid:eeee1321-4af5-424c-a0e1-ed3aab1c349d",
        "resourceType": "Organization",
        "name": "MacRitchie Laboratory",
        "type": "Accredited Laboratory",
        "contact": {
          "telecom": [
            {
              "system": "phone",
              "value": "+6562711188"
            }
          ],
          "address": {
            "type": "physical",
            "use": "work",
            "text": "2 Thomson Avenue 4 Singapore 098888"
          }
        }
      }
    ]
  }
}

=== Open-Attestation/schemata/src/sg/gov/moh/pdt-healthcert/1.0/sample-document.json
{
  "id": "TEST001",
  "name": "HealthCert",
  "validFrom": "2021-05-18T06:43:12.152Z",
  "fhirVersion": "4.0.1",
  "fhirBundle": {
    "resourceType": "Bundle",
    "type": "collection",
    "entry": [
      {
        "resourceType": "Patient",
        "extension": [
          {
            "url": "http://hl7.org/fhir/StructureDefinition/patient-nationality",
            "code": {
              "text": "SG"
            }
          }
        ],
        "identifier": [
          {
            "type": "PPN",
            "value": "E7831177G"
          },
          {
            "type": {
              "text": "NRIC"
            },
            "value": "S9098989Z"
          }
        ],
        "name": [
          {
            "text": "Tan Chen Chen"
          }
        ],
        "gender": "female",
        "birthDate": "1990-01-15"
      },
      {
        "resourceType": "Specimen",
        "type": {
          "coding": [
            {
              "system": "http://snomed.info/sct",
              "code": "258500001",
              "display": "Nasopharyngeal swab"
            }
          ]
        },
        "collection": {
          "collectedDateTime": "2020-09-27T06:15:00Z"
        }
      },
      {
        "resourceType": "Observation",
        "identifier": [
          {
            "value": "123456789",
            "type": "ACSN"
          }
        ],
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "94531-1",
              "display": "Reverse transcription polymerase chain reaction (rRT-PCR) test"
            }
          ]
        },
        "valueCodeableConcept": {
          "coding": [
            {
              "system": "http://snomed.info/sct",
              "code": "260385009",
              "display": "Negative"
            }
          ]
        },
        "effectiveDateTime": "2020-09-28T06:15:00Z",
        "status": "final",
        "performer": {
          "name": [
            {
              "text": "Dr Michael Lim"
            }
          ]
        },
        "qualification": [
          {
            "identifier": "MCR 123214",
            "issuer": "MOH"
          }
        ]
      },
      {
        "resourceType": "Organization",
        "name": "MacRitchie Medical Clinic",
        "type": "Licensed Healthcare Provider",
        "endpoint": {
          "address": "https://www.macritchieclinic.com.sg"
        },
        "contact": {
          "telecom": [
            {
              "system": "phone",
              "value": "+6563113111"
            }
          ],
          "address": {
            "type": "physical",
            "use": "work",
            "text": "MacRitchie Hospital Thomson Road Singapore 123000"
          }
        }
      },
      {
        "resourceType": "Organization",
        "name": "MacRitchie Laboratory",
        "type": "Accredited Laboratory",
        "contact": {
          "telecom": [
            {
              "system": "phone",
              "value": "+6562711188"
            }
          ],
          "address": {
            "type": "physical",
            "use": "work",
            "text": "2 Thomson Avenue 4 Singapore 098888"
          }
        }
      }
    ]
  }
}
